### PR TITLE
[ROCm] Added include of hipblas.h in hipblaslt_wrapper.h

### PR DESCRIPTION
**Pull request by jayfurmanek**
Fixed issue from SWDEV-482396 for rocm-jaxlib-v0.4.30-qa branch.

### CODE REVIEW

**Review by Ruturaj4 — APPROVED** [review]
LGTM, or maybe just remove if/else and keep both?

**Review by zoranjovanovic-ns — APPROVED** [review]
LGTM

**Comment by i-chaochen** [comment]
IIUC this fix is because that hipblaslt recently changed the dependent lib(header) from hipblas package to hipblas-common package.

may I ask is it for all ROCm version or just ROCm6.2+ ? what about previous ROCm versions? e.g., 6.1, 6.0 or 5.7? 

@jayfurmanek @Ruturaj4 @zoranjovanovic-ns

**Comment by draganmladjenovic** [comment]
The fix will work on previous versions too, but I think this is primarily a fix for 6.3?

**Comment by i-chaochen** [comment]
Yes, we need this ROCm 6.3 patch for previous QA branches as well. 

In addition, shall we upstream this fix for JAX/TF/XLA on rocm6.3?

**Pull request merged**
